### ISSUE TITLE
where is the example_usage.py code?

### ISSUE THREAD

**Issue by alfredtorres** [lisaGUZZI/Soft-morph#1]
Thanks for your interesting work!
But, I cannot find the example_usage.py ?

Best regards!

**Comment by alfredtorres** [comment]
another problem is in `class SoftSkeletonizer3D`, maybe no definition of `self.cube_size`.

**Comment by lisaGUZZI** [comment]
Hello, thanks for your comments. The example_usage.py has just been uploaded and the class SoftSkeletonizer3D class debugged.
