### ISSUE TITLE
Attribute error using SoftMorph3D.SoftSkeletonizer3D()

### ISSUE THREAD

**Issue by wooseung-kim** [lisaGUZZI/Soft-morph#2]
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/078733c8-644a-46c9-ae94-b3a9c12892bc">

I got attribute error using SoftMorph3D.SoftSkeletonizer3D(). Can I get any help?

**Comment by lisaGUZZI** [comment]
Hello, thanks for your feedback. This class has recently been debugged. It should be working now!
